### ISSUE TITLE
Add Readme.md for the Application

### ISSUE THREAD

**Issue by ankurg132** [Pulkiteleven/Guardian#4]
This repository contains no documentation currently and we should add a Readme.md file to show some information about the repository.
You can take the inspiration from [the Semikolan website](https://github.com/semikolan-co/semikolan-react).

**Comment by najeebkp** [comment]
Hi @ankurg132  please assign me this task

**Comment by ankurg132** [comment]
@najeebkp also embed this YouTube [video](https://www.youtube.com/watch?v=CgYKJM_daHo) in the Readme, you can also take it's inspiration to create the application description.
